Project/Project/urls.py
#coding:utf-8
from django.conf.urls import include, url, patterns
from django.contrib import admin
from Project import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login,logout
from pets_adopt.views import pet,user


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    #url(r'',include('social_auth.urls')),
    url(r'^$', 'pets_adopt.views.pet.index', name='index'),
    url(r'^signup/$', 'pets_adopt.views.user.user_signup', name='signup'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'index'}, name='logout'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'pets_adopt/login.html'}, name='login'),
    url(r'^user_edit/(?P<user_id>\d+)/$', 'pets_adopt.views.user.user_edit', name='user_edit'),
    url(r'^post/new/$', 'pets_adopt.views.pet.new_pet', name='new_pets'),
    url(r'^post/detail/(?P<pets_id>\d+)/$', 'pets_adopt.views.pet.pet_detail', name='pet_detail'),
    url(r'^post/adopt/(?P<pets_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt', name='pet_adopt'),
    url(r'^post/adopt/success/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_success', name='pet_adopt_success'),
    url(r'^check_response/$', 'pets_adopt.views.pet.user_check_response', name='check_all'),
    url(r'^check_confirm/$', 'pets_adopt.views.pet.user_check_confirm', name='user_check_confirm'),
    url(r'^check_response/pet_confirm/1/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_first_confirm', name='pet_adopt_first_confirm'),
    url(r'^check_confirm/pet_confirm/2/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_second_confirm', name='pet_adopt_second_confirm'),
    url(r'^check_response/pet_confirm/last/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_last_confirm', name='pet_adopt_last_confirm'),
    url(r'^blog/(?P<pets_id>\d+)/$', 'pets_adopt.views.blog.post_list', name='post_list'),
    url(r'^blog/new/(?P<pets_id>\d+)/$', 'pets_adopt.views.blog.post_new', name='post_new'),
    url(r'^user_detail/(?P<user_id>\d+)/$', 'pets_adopt.views.user.user_detail', name='user_detail'),
    url(r'^member_center/(?P<user_id>\d+)/$', 'pets_adopt.views.center.main', name='center_main'),
    url(r'^member_center/my_pet/(?P<user_id>\d+)/$', 'pets_adopt.views.center.my_pet', name='my_pet'),
    url(r'^member_center/sending_pet/(?P<user_id>\d+)/$', 'pets_adopt.views.center.sending_pet', name='sending_pet'),
    url(r'^member_center/receiving_pet/(?P<user_id>\d+)/$', 'pets_adopt.views.center.receiving_pet', name='receiving_pet'),

    url(r'^questionnaire/$', 'pets_adopt.views.blog.question_index', name='questionnaire'),
    url(r'^question_result/$', 'pets_adopt.views.blog.question_handle', name='question_handle'),
    url(r'^pet_search/$', 'pets_adopt.views.pet.pet_search', name='pet_search'),
)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/pets_adopt/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone


class NewUser(AbstractUser):  # (username,email,password1,password2)
    sex_choice = (
        ('m', u'男'),
        ('f', u'女'),
    )

    name = models.CharField(u'姓名', max_length=20, default='')
    gender = models.CharField(u'性別', max_length=1,  choices=sex_choice, default='m')
    id_card_num = models.CharField(u'身份證字號', max_length=10, default='')
    mobile = models.CharField(u'手機號碼', max_length=10, default='')
    home_tel = models.CharField(u'家電', max_length=11, default='')
    address = models.CharField(u'地址', max_length=50, default='')
    facebook = models.CharField(u'Facebook', max_length=100, default='')
    line = models.CharField(u'Line', max_length=20, default='')
    profile = models.TextField(u'個人自述', max_length=200, default='')
    photo = models.ImageField(u'身份證照片',upload_to='person',null=True)

    def __unicode__(self):
        return self.name


class Comment(models.Model):
    credit = (
        (0, u'優良'),
        (1, u'普通'),
        (2, u'不良'),
    )
    person = models.ForeignKey(settings.AUTH_USER_MODEL)
    comment = models.TextField(u'評語')
    credit = models.IntegerField(u'信用', choices=credit, default=0)

    def __unicode__(self):
        return self.comment

class Pets(models.Model):
    pet_status_choice = (
        (0, u'待認養'),
        (1, u'已領養'),
    )
    chip_choice = (
        (True, u'有'),
        (False, u'無'),
    )
    neuter_choice = (
        (True, u'有'),
        (False, u'無'),
    )
    dog_or_cat_choice = (
        (0, u'狗'),
        (1, u'貓'),
    )
    sex_choice = (
        (True,u'男生'),
        (False,u'女生'),
    )
    area_choice = (
        (0, u'台北市'),
        (1, u'新北市'),
        (2, u'桃園市'),
        (3, u'新竹縣'),
        (4, u'新竹市'),
        (5, u'苗栗縣'),
        (6, u'台中市'),
        (7, u'彰化縣'),
        (8, u'南投縣'),
        (9, u'雲林縣'),
        (10, u"嘉義縣"),
        (11, u'嘉義市'),
        (12, u'台南市'),
        (13, u'高雄市'),
        (14, u'屏東縣'),
        (15, u'台東縣'),
        (16, u'花蓮縣'),
        (17, u'宜蘭縣'),

    )
    size_choice = (
        (0,u'小型'),
        (1,u'中型'),
        (2,u'大型'),
    )
    age_choice = (
        (0,u'幼年'),
        (1,u'成年'),
    )
    color_choice = (
        (0,u'白色'),
        (1,u'黑色'),
        (2,u'棕色'),
        (3,u'黃色'),
        (4,u'花色'),
        (5,u'虎班'),
        (6,u'其他')
    )
    pet_owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='current_owner',default='')
    pet_publisher = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='previous_owner',default='')
    pet_name = models.CharField(u'寵物名', max_length=30, default='')
    state = models.IntegerField(u'領養狀態', choices=pet_status_choice, default=0)
    content = models.TextField(u'寵物簡介')
    color = models.IntegerField(u'毛色', choices=color_choice, default=0)
    chip = models.BooleanField(u'晶片有無', choices=chip_choice, default=False)
    neuter = models.BooleanField(u'是否有結紮', choices=neuter_choice, default=False)
    dog_or_cat = models.IntegerField(u'狗或貓', choices=dog_or_cat_choice, default=0)
    area = models.IntegerField(u'寵物所在地區', choices=area_choice, default=0)
    breed = models.CharField(u'品種', max_length=20, default='')
    age = models.IntegerField(u'年紀', choices=age_choice, default=0)
    sex = models.BooleanField(u'寵物性別',choices=sex_choice,default=True)
    size = models.IntegerField(u'體型',choices=size_choice,default=0)
    photo = models.ImageField(upload_to='pet', null=True)

    def __unicode__(self):
        return self.pet_name


class Adopt(models.Model):
    mode = (
        (0, u'待批准'),
        (1, u'通過'),
        (2, u'拒絕'),
        (3, u'待領養者確認'),
        (4, u'待送養者確認'),
    )
    adopt_person = models.ForeignKey(settings.AUTH_USER_MODEL)
    adopt_pet = models.ForeignKey(Pets)
    mode = models.IntegerField(u'審核狀態', choices=mode, default=0)
    content = models.TextField(u'認養理由')

    def __unicode__(self):
        return unicode(self.adopt_person)


class Blog(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    pet = models.ForeignKey(Pets)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=1000)
    published_date = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(upload_to='article',null=True)

    def __unicode__(self):
        return self.title


"""
class visit_msg(models.Model):
    mode = (
        (0,u'待批准'),
        (1,u'通過'),
        (2,u'拒'),
    )
    visitor = models.ForeignKey(settings.AUTH_USER_MODEL)
    visit_pet = models.ForeignKey(Pets)
    content = models.TextField(u'給主人的話')
    visit_date = models.DateTimeField(u'探訪時間')
"""

Project/pets_adopt/forms.py
# coding:utf-8
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from models import Pets,Adopt,Blog,Comment
from django.utils.safestring import mark_safe

class HorizRadioRenderer(forms.RadioSelect.renderer): #自訂radio選項redner樣式
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
            """Outputs radios"""
            return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class UserForm(UserCreationForm):
    name = forms.CharField(label='姓名',max_length=20,required=True)
    facebook = forms.CharField(label='Facebook網址',max_length=100,required=True)
    address = forms.CharField(label='地址',max_length=50,required=True)
    mobile = forms.CharField(label='手機號碼',max_length=10,required=True)
    id_card_num = forms.CharField(label='身份證字號',max_length=10,required=True)
    line = forms.CharField(label='Line ID(非必填)',max_length=20,required=False)
    home_tel = forms.CharField(label='家電(非必填)',max_length=10,required=False)
    photo = forms.ImageField(label='身份證照')
    class Meta:
        model = get_user_model()
        fields = ('username','name','gender','email','id_card_num','address','mobile','home_tel','facebook','line','profile','photo')
        labels = {
            'username': '帳號',
            'email': 'E-mail',
            'gender': '性別',
            'profile': '個人自述',
        }

class User_Edit(forms.ModelForm):
    line = forms.CharField(label='Line ID(非必填)',max_length=20,required=False)
    home_tel = forms.CharField(label='家電(非必填)',max_length=10,required=False)
    class Meta():
        model = get_user_model()
        fields = ('email','profile','mobile','home_tel','facebook','line','profile')

'''class Change_User_State(forms.ModelForm):
    class Meta():
        model = get_user_model()
        fields = ('state',)
'''

class LoginForm(forms.Form):
    username = forms.CharField(label='帳號',max_length=255, required=True)
    password = forms.CharField(label='密碼',widget=forms.PasswordInput, required=True)

class Post_Pet(forms.ModelForm):
    photo = forms.ImageField(label='放張寵物照')
    breed = forms.CharField(label='品種(非必填)',max_length=10,required=False)
    class Meta:
        model = Pets
        fields = ('dog_or_cat','pet_name','sex','age','size','color','breed','area','chip','neuter','content','photo')
        labels = {
            'dog_or_cat':'狗或貓',
            'pet_name':'寵物的名字',
            'sex':'寵物性別',
            'age':'年紀',
            'size':'體型',
            'color':'毛色',
            'area':'地區',
            'chip':'晶片有無',
            'neuter':'有無結紮',
            'content':'寵物介紹一下',
        }
        widgets = {
            'dog_or_cat': forms.RadioSelect(renderer=HorizRadioRenderer),
            'chip': forms.RadioSelect(renderer=HorizRadioRenderer),
            'neuter': forms.RadioSelect(renderer=HorizRadioRenderer),
        }


class Adopt_Request_Form(forms.ModelForm):
    class Meta:
        model = Adopt
        fields = ('content',)


class Blog_Post(forms.ModelForm):
    photo = forms.ImageField(label='上傳照片')
    class Meta:
        model = Blog
        fields = ('title','content','photo')
        labels = {
            'title':'標題',
            'content':'內容',
        }


class Comment_Form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('credit','comment',)
        labels = {
            'credit':'給送養者評價',
            'comment':'寫下你對對方的評語',
        }
        widgets = {
            'credit': forms.RadioSelect(renderer=HorizRadioRenderer)
        }

Project/pets_adopt/views/blog.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from pets_adopt.forms import Blog_Post
from pets_adopt.models import Pets,Adopt
from pets_adopt.models import Blog
from django.utils import timezone



def post_list(request, pets_id):
    template = 'pets_adopt/blog/post_list.html'
    pet = get_object_or_404(Pets, id=pets_id)
    blog = Blog.objects.filter(pet = pet)
    can_post = False
    if (pet.pet_owner == request.user):
        can_post = True
    return render(request, template, {'posts': blog, 'pet': pet,'can_post':can_post})


def post_new(request, pets_id):
    template = 'pets_adopt/blog/post_new.html'
    pet = get_object_or_404(Pets, id=pets_id)
    if request.method == 'POST':
        form = Blog_Post(request.POST, request.FILES)
        if form.is_valid:
            image_file = request.FILES["photo"]
            blog = form.save(commit=False)
            blog.photo = image_file
            blog.author = request.user
            blog.pet= pet
            blog.published_date = timezone.now()
            blog.save()
            return redirect('post_list', pets_id=pet.id)
    else:
        form = Blog_Post()
        return render(request, template, {'pet': pet, 'form': form})


def question_index(request):
    template = 'pets_adopt/extra/questionnaire.html'
    return render(request, template, {'nbar': 'question'})


def question_handle(request):
    template = 'pets_adopt/extra/question_result.html'
    result = 0
    right = False
    for i in range(1, 11):
        if request.POST.get('Q' + str(i)) == 'T':
            result += 10
    if result >= 70:
        right = True
    return render(request, template, {'right': right, 'result': result, 'nbar': 'question'})

Project/pets_adopt/views/center.py
#coding:utf-8
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from pets_adopt.models import Pets,Adopt,NewUser

@login_required
def main(request,user_id): #會員中心，可修改個人資料及寵物資料，以及觀看送領養紀錄
    user = get_object_or_404(NewUser, id=user_id)
    template_name = "pets_adopt/member_center/main.html"
    return render(request,template_name,{'user': user,'nbar':'memcenter'})


@login_required
def my_pet(request, user_id): #屬於我的寵物
    template_name = "pets_adopt/member_center/my_pet.html"
    user = get_object_or_404(NewUser, id=user_id)
    pet = Pets.objects.filter(pet_owner=user)
    return render(request, template_name, {'user':user,'pet':pet,'nbar':'memcenter'})

# Adopt.mode=0:待批準,1:通過,2:拒絕,3:待領養者確認,4:待送養者確認
@login_required
def sending_pet(request, user_id): #送養中的寵物
    template_name = "pets_adopt/member_center/sending_pet.html"
    user = get_object_or_404(NewUser, id=user_id)
    pet = Pets.objects.filter(pet_publisher=user, state=0)
    return render(request, template_name, {'user':user,'pet':pet,'nbar':'memcenter'})

@login_required
def receiving_pet(request, user_id): #想領養的寵物
    template_name = "pets_adopt/member_center/receiving_pet.html"
    user = get_object_or_404(NewUser, id=user_id)
    adopts = Adopt.objects.filter(adopt_person=user) #這個人的所有領養單
    return render(request, template_name, {'user':user,'adopt':adopts,'nbar':'memcenter'})

Project/pets_adopt/views/user.py
#coding:utf-8
from django.contrib.auth import login, authenticate
from django.contrib import messages,auth
from pets_adopt.forms import UserForm,User_Edit
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from pets_adopt.models import NewUser,Adopt,Pets,Comment


def user_signup(request):
    template_name = 'pets_adopt/signup.html'
    if request.method == 'POST':
        form = UserForm(request.POST,request.FILES)
        if form.is_valid():
            image_file = request.FILES["photo"]
            user_name = request.POST['username']
            password = form.clean_password2()
            form.save(commit=False)
            form.photo = image_file
            form.save()
            user = authenticate(username = user_name, password = password)
            if user.is_active:
                login(request,user)
                messages.success(request,u'註冊成功並登錄')
            return redirect('index')
    else:
        form = UserForm
    return render(request,template_name,{'form': form,'nbar':'signup'})

@login_required
def user_edit(request,user_id): #要尋找更好寫法
    user = get_object_or_404(NewUser, id=user_id)
    template_name = "pets_adopt/user_edit.html"
    if request.method =='POST':
        form = User_Edit(request.POST, instance=user)
        form.save()
        messages.success(request,u'修改成功')
        return redirect('index')
    else:
        form = User_Edit(instance = user)
        return render(request,template_name,{'form':form,'user':user})


def user_detail(request,user_id):
    usr = get_object_or_404(NewUser, id=user_id)
    template_name = "pets_adopt/user_detail.html"
    all_comment = Comment.objects.filter(person = usr)
    all_pet = Pets.objects.filter(pet_owner=usr)
    good = 0
    ok = 0
    bad = 0
    for cmt in all_comment: #顯示這個人的評價
        if cmt.credit == 0:
            good += 1
        elif cmt.credit == 1:
            ok += 1
        elif cmt.credit == 2:
            bad += 1
    return render(request,template_name, {'usr':usr,'all_comment':all_comment,'good':good,'ok':ok,'bad':bad,'all_pet':all_pet})




"""
def user_login(request):
    template_name = 'pets_adopt/login.html'
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid:
            user_name = request.POST['username']
            password = request.POST['password']
            user = authenticate(username = user_name,password = password)
            if user is not None and user.is_active:
                login(request, user)
                    return redirect('index')

    else:
        form = LoginForm()
        return render(request,template_name,{'form': form})
"""

"""

def user_logout(request):
    auth.logout(request)
    return redirect('index')
"""

Project/templates/pets_adopt/index.html
{% extends "pets_adopt/base.html" %}
{% load staticfiles %}
{% block extend_css %}
    <style type="text/css">
    .carousel-caption {
  margin-bottom: 150px;
}
    </style>
{% endblock %}
{% block carousel %}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="{% static 'carousel/dog1.jpg' %}" class="first-slide" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>歡迎來到，狗日子的第十三日</h1>
          <h3>我們希望，所有的流浪動物都能有個家</h3>
          <p><a class="btn btn-lg btn-primary" href="{% url 'questionnaire' %}" role="button">請先進行自我評估</a></p>
        </div>
      </div>
    </div>

    <div class="item">
      <img src="{% static 'carousel/cat1.jpg' %}" class="second-slide" alt="Second-slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>支持流浪貓狗絕育計畫</h1>
          <p><a class="btn btn-lg btn-primary" href="http://www.tnrtw.org/" role="button" target="_blank">助紮計畫</a></p>
        </div>
      </div>
    </div>

    <div class="item">
      <img src="{% static 'carousel/dog2.jpg' %}" class="third-slide" alt="Third-slide">
      <div class="container">
        <div class="carousel-caption">
          <h1 style="color:black;">認養零距離</h1>
          <h3 style="color:black;">請以認養代替購買</h3>
        </div>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}
{% block content %}

    <div class="row index-pet-show">
      <div class="col-lg-6">
      <h3>我想有個家</h3>
      {% for show in pet_not_adopt %}
            <div class="row pet-search-item">
                <div class="col-md-3">
                    <img src="{{ MEDIA_URL }}{{ show.photo }}" class="img-thumbnail"
                         height="128px" width="128px">
                </div>
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-sm-4">
                            <p>名字：<a href="{% url 'pet_detail' pets_id=show.id %}">{{ show.pet_name }}</a></p>
                        </div>
                        <div class="col-sm-4">
                            <p>體型：{{ show.get_size_display }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p>性別：{{ show.get_sex_display }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>種類：{{ show.get_dog_or_cat_display }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p>地區：{{ show.get_area_display }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p>毛色：{{ show.get_color_display }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p>簡介：{{ show.content | safe | truncatechars_html:40 }}</p>
                        </div>
                    </div>
                </div>
            </div>
      {% endfor %}
      </div>
      <div class="row index-pet-show">
        <div class="col-lg-6">
      <h3>我有新家了</h3>
      {% for show in pet_have_adopt %}
            <div class="row pet-search-item">
                <div class="col-md-3">
                    <img src="{{ MEDIA_URL }}{{ show.photo }}" class="img-thumbnail"
                         height="128px" width="128px">
                </div>
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-sm-4">
                            <p>名字：<a href="{% url 'pet_detail' pets_id=show.id %}">{{ show.pet_name }}</a></p>
                        </div>
                        <div class="col-sm-4">
                            <p>體型：{{ show.get_size_display }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p>性別：{{ show.get_sex_display }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>種類：{{ show.get_dog_or_cat_display }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p>地區：{{ show.get_area_display }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p>毛色：{{ show.get_color_display }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p>簡介：{{ show.content | safe | truncatechars_html:40 }}</p>
                        </div>
                    </div>
                </div>
            </div>
      {% endfor %}
        </div>
      </div>
   </div>
 {% endblock %}

Project/templates/pets_adopt/login.html
{% extends "pets_adopt/base.html" %}

{% block content %}
    <div id="login-contain">
<h1>登入</h1>
    <!--<a href="{'% url "socialauth_begin" "facebook" %}">FB登入</a> -->
<form method="POST" action="{% url 'login' %}" id="login-form" class="form-horizontal">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
    {{ form.username.errors }}
    <label for="{{ form.username.id_for_label }}" class="col-sm-2 control-label">帳號:</label>
        <div class="col-sm-10">
        {{ form.username }}
        </div>
    </div>

    <div class="form-group">
    {{ form.password.errors }}
    <label for="{{ form.password.id_for_label }}" class="col-sm-2 control-label">密碼:</label>
        <div class="col-sm-10">
        {{ form.password }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">送出</button>
        </div>
    </div>
</form>
    </div>
{% endblock %}

Project/templates/pets_adopt/pets_detail.html
{% extends "pets_adopt/base.html" %}

{% block content %}

<div id="pet-detail-contain">
    <div class="row">
        <div class="col-md-3">
            <div class="post-detail-right-part">
                <a class="btn btn-default" href="/blog/{{ pet.id }}" role="button">
                    看看{{ pet.pet_name }}的日誌
                </a>
            </div>
            <div class="post-detail-right-part">
            {% if user.is_authenticated %}
                {% if can_adopt == 2 %}
                <a href="#">
                    <button type="submit" class="btn btn-default">{{ pet.pet_name }}已經被領養走了</button>
                </a>
                {% elif can_adopt == 1 %}
                <a href="#">
                    <button type="submit" class="btn btn-default">你是{{ pet.pet_name }}的主人</button>
                </a>
                {% else %}
                <a href="/post/adopt/{{ pet.id }}">
                    <button type="submit" class="btn btn-default">我要領養{{ pet.pet_name }}</button>
                </a>
                {% endif %}

            {% else %}
                 <a href="{% url 'login' %}">
                    <button type="submit" class="btn btn-default">請先登入</button>
                </a>
            {% endif %}
            </div>

            <div class="post-detail-right-part">
            {% if pet.state == 1 %}
                <a href="{% url 'user_detail' user_id=pet.pet_owner.id %}"
                   class="btn btn-default" role="button">新主人{{ pet.pet_owner }}</a>
            {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <table class="table table-hover">
              <tr>
                <td>送養者</td>
                <td><a href="{% url 'user_detail' user_id=pet.pet_publisher.id %}">
                    {{ pet.pet_publisher }}</a></td>
              </tr>
                <tr>
                    <td>狗狗名字</td>
                    <td>{{ pet.pet_name }}</td>
                </tr>
                <tr>
                    <td>狗狗領養狀態</td>
                    <td>{{ pet.get_state_display }}</td>
                </tr>
                <tr>
                    <td>毛色</td>
                    <td>{{ pet.get_color_display }}</td>
                </tr>
                <tr>
                    <td>結紮</td>
                    <td>{{ pet.get_neuter_display }}</td>
                </tr>
                <tr>
                    <td>晶片</td>
                    <td>{{ pet.get_chip_display }}</td>
                </tr>
                <tr>
                    <td>狗狗介紹</td>
                    <td>{{ pet.content }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <img src="{{ MEDIA_URL }}{{ pet.photo }}" id="pet-detail-picture">
        </div>
    </div>

</div>

{% endblock %}