Project/Project/urls.py
#coding:utf-8
from django.conf.urls import include, url, patterns
from django.contrib import admin
from Project import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login,logout
from pets_adopt.views import pet,user


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    #url(r'',include('social_auth.urls')),
    url(r'^$', 'pets_adopt.views.pet.index', name='index'),
    url(r'^signup/$', 'pets_adopt.views.user.user_signup', name='signup'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'index'}, name='logout'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'pets_adopt/login.html'}, name='login'),
    url(r'^user_edit/(?P<user_id>\d+)/$', 'pets_adopt.views.user.user_edit', name='user_edit'),
    url(r'^post/new/$', 'pets_adopt.views.pet.new_pet', name='new_pets'),
    url(r'^post/detail/(?P<pets_id>\d+)/$', 'pets_adopt.views.pet.pet_detail', name='pet_detail'),
    url(r'^post/adopt/(?P<pets_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt', name='pet_adopt'),
    url(r'^post/adopt/success/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_success', name='pet_adopt_success'),
    url(r'^check_response/$', 'pets_adopt.views.pet.user_check_response', name='check_all'),
    url(r'^check_confirm/$', 'pets_adopt.views.pet.user_check_confirm', name='user_check_confirm'),
    url(r'^check_response/pet_confirm/1/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_first_confirm', name='pet_adopt_first_confirm'),
    url(r'^check_confirm/pet_confirm/2/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_second_confirm', name='pet_adopt_second_confirm'),
    url(r'^check_response/pet_confirm/last/(?P<adopt_id>\d+)/$', 'pets_adopt.views.pet.pet_adopt_last_confirm', name='pet_adopt_last_confirm'),
    url(r'^blog/(?P<pets_id>\d+)/$', 'pets_adopt.views.blog.post_list', name='post_list'),
    url(r'^blog/new/(?P<pets_id>\d+)/$', 'pets_adopt.views.blog.post_new', name='post_new'),
    url(r'^user_detail/(?P<user_id>\d+)/$', 'pets_adopt.views.user.user_detail', name='user_detail'),
    url(r'^member_center/(?P<user_id>\d+)/$', 'pets_adopt.views.center.main', name='center_main'),
    url(r'^member_center/my_pet/(?P<user_id>\d+)/$', 'pets_adopt.views.center.my_pet', name='my_pet'),
    url(r'^member_center/sending_pet/(?P<user_id>\d+)/$', 'pets_adopt.views.center.sending_pet', name='sending_pet'),
    url(r'^member_center/receiving_pet/(?P<user_id>\d+)/$', 'pets_adopt.views.center.receiving_pet', name='receiving_pet'),

    url(r'^questionnaire/$', 'pets_adopt.views.blog.question_index', name='questionnaire'),
    url(r'^question_result/$', 'pets_adopt.views.blog.question_handle', name='question_handle'),
    url(r'^pet_search/$', 'pets_adopt.views.pet.pet_search', name='pet_search'),
)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/pets_adopt/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone


class NewUser(AbstractUser):  # (username,email,password1,password2)
    sex_choice = (
        ('m', u'男'),
        ('f', u'女'),
    )

    name = models.CharField(u'姓名', max_length=20, default='')
    gender = models.CharField(u'性別', max_length=1,  choices=sex_choice, default='m')
    id_card_num = models.CharField(u'身份證字號', max_length=10, default='')
    mobile = models.CharField(u'手機號碼', max_length=10, default='')
    home_tel = models.CharField(u'家電', max_length=11, default='')
    address = models.CharField(u'地址', max_length=50, default='')
    facebook = models.CharField(u'Facebook', max_length=100, default='')
    line = models.CharField(u'Line', max_length=20, default='')
    profile = models.TextField(u'個人自述', max_length=200, default='')
    photo = models.ImageField(u'身份證照片',upload_to='person',null=True)

    def __unicode__(self):
        return self.name


class Comment(models.Model):
    credit = (
        (0, u'優良'),
        (1, u'普通'),
        (2, u'不良'),
    )
    person = models.ForeignKey(settings.AUTH_USER_MODEL)
    comment = models.TextField(u'評語')
    credit = models.IntegerField(u'信用', choices=credit, default=0)

    def __unicode__(self):
        return self.comment

class Pets(models.Model):
    pet_status_choice = (
        (0, u'待認養'),
        (1, u'已領養'),
    )
    chip_choice = (
        (True, u'有'),
        (False, u'無'),
    )
    neuter_choice = (
        (True, u'有'),
        (False, u'無'),
    )
    dog_or_cat_choice = (
        (0, u'狗'),
        (1, u'貓'),
    )
    sex_choice = (
        (True,u'男生'),
        (False,u'女生'),
    )
    area_choice = (
        (0, u'台北市'),
        (1, u'新北市'),
        (2, u'桃園市'),
        (3, u'新竹縣'),
        (4, u'新竹市'),
        (5, u'苗栗縣'),
        (6, u'台中市'),
        (7, u'彰化縣'),
        (8, u'南投縣'),
        (9, u'雲林縣'),
        (10, u"嘉義縣"),
        (11, u'嘉義市'),
        (12, u'台南市'),
        (13, u'高雄市'),
        (14, u'屏東縣'),
        (15, u'台東縣'),
        (16, u'花蓮縣'),
        (17, u'宜蘭縣'),

    )
    size_choice = (
        (0,u'小型'),
        (1,u'中型'),
        (2,u'大型'),
    )
    age_choice = (
        (0,u'幼年'),
        (1,u'成年'),
    )
    color_choice = (
        (0,u'白色'),
        (1,u'黑色'),
        (2,u'棕色'),
        (3,u'黃色'),
        (4,u'花色'),
        (5,u'虎班'),
        (6,u'其他')
    )
    pet_owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='current_owner',default='')
    pet_publisher = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='previous_owner',default='')
    pet_name = models.CharField(u'寵物名', max_length=30, default='')
    state = models.IntegerField(u'領養狀態', choices=pet_status_choice, default=0)
    content = models.TextField(u'寵物簡介')
    color = models.IntegerField(u'毛色', choices=color_choice, default=0)
    chip = models.BooleanField(u'晶片有無', choices=chip_choice, default=False)
    neuter = models.BooleanField(u'是否有結紮', choices=neuter_choice, default=False)
    dog_or_cat = models.IntegerField(u'狗或貓', choices=dog_or_cat_choice, default=0)
    area = models.IntegerField(u'寵物所在地區', choices=area_choice, default=0)
    breed = models.CharField(u'品種', max_length=20, default='')
    age = models.IntegerField(u'年紀', choices=age_choice, default=0)
    sex = models.BooleanField(u'寵物性別',choices=sex_choice,default=True)
    size = models.IntegerField(u'體型',choices=size_choice,default=0)
    photo = models.ImageField(upload_to='pet', null=True)

    def __unicode__(self):
        return self.pet_name


class Adopt(models.Model):
    mode = (
        (0, u'待批准'),
        (1, u'通過'),
        (2, u'拒絕'),
        (3, u'待領養者確認'),
        (4, u'待送養者確認'),
    )
    adopt_person = models.ForeignKey(settings.AUTH_USER_MODEL)
    adopt_pet = models.ForeignKey(Pets)
    mode = models.IntegerField(u'審核狀態', choices=mode, default=0)
    content = models.TextField(u'認養理由')

    def __unicode__(self):
        return unicode(self.adopt_person)


class Blog(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    pet = models.ForeignKey(Pets)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=1000)
    published_date = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(upload_to='article',null=True)

    def __unicode__(self):
        return self.title


"""
class visit_msg(models.Model):
    mode = (
        (0,u'待批准'),
        (1,u'通過'),
        (2,u'拒'),
    )
    visitor = models.ForeignKey(settings.AUTH_USER_MODEL)
    visit_pet = models.ForeignKey(Pets)
    content = models.TextField(u'給主人的話')
    visit_date = models.DateTimeField(u'探訪時間')
"""

Project/pets_adopt/forms.py
# coding:utf-8
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from models import Pets,Adopt,Blog,Comment
from django.utils.safestring import mark_safe

class HorizRadioRenderer(forms.RadioSelect.renderer): #自訂radio選項redner樣式
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
            """Outputs radios"""
            return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class UserForm(UserCreationForm):
    name = forms.CharField(label='姓名',max_length=20,required=True)
    facebook = forms.CharField(label='Facebook網址',max_length=100,required=True)
    address = forms.CharField(label='地址',max_length=50,required=True)
    mobile = forms.CharField(label='手機號碼',max_length=10,required=True)
    id_card_num = forms.CharField(label='身份證字號',max_length=10,required=True)
    line = forms.CharField(label='Line ID(非必填)',max_length=20,required=False)
    home_tel = forms.CharField(label='家電(非必填)',max_length=10,required=False)
    photo = forms.ImageField(label='身份證照')
    class Meta:
        model = get_user_model()
        fields = ('username','name','gender','email','id_card_num','address','mobile','home_tel','facebook','line','profile','photo')
        labels = {
            'username': '帳號',
            'email': 'E-mail',
            'gender': '性別',
            'profile': '個人自述',
        }

class User_Edit(forms.ModelForm):
    line = forms.CharField(label='Line ID(非必填)',max_length=20,required=False)
    home_tel = forms.CharField(label='家電(非必填)',max_length=10,required=False)
    class Meta():
        model = get_user_model()
        fields = ('email','profile','mobile','home_tel','facebook','line','profile')

'''class Change_User_State(forms.ModelForm):
    class Meta():
        model = get_user_model()
        fields = ('state',)
'''

class LoginForm(forms.Form):
    username = forms.CharField(label='帳號',max_length=255, required=True)
    password = forms.CharField(label='密碼',widget=forms.PasswordInput, required=True)

class Post_Pet(forms.ModelForm):
    photo = forms.ImageField(label='放張寵物照')
    breed = forms.CharField(label='品種(非必填)',max_length=10,required=False)
    class Meta:
        model = Pets
        fields = ('dog_or_cat','pet_name','sex','age','size','color','breed','area','chip','neuter','content','photo')
        labels = {
            'dog_or_cat':'狗或貓',
            'pet_name':'寵物的名字',
            'sex':'寵物性別',
            'age':'年紀',
            'size':'體型',
            'color':'毛色',
            'area':'地區',
            'chip':'晶片有無',
            'neuter':'有無結紮',
            'content':'寵物介紹一下',
        }
        widgets = {
            'dog_or_cat': forms.RadioSelect(renderer=HorizRadioRenderer),
            'chip': forms.RadioSelect(renderer=HorizRadioRenderer),
            'neuter': forms.RadioSelect(renderer=HorizRadioRenderer),
        }


class Adopt_Request_Form(forms.ModelForm):
    class Meta:
        model = Adopt
        fields = ('content',)


class Blog_Post(forms.ModelForm):
    photo = forms.ImageField(label='上傳照片')
    class Meta:
        model = Blog
        fields = ('title','content','photo')
        labels = {
            'title':'標題',
            'content':'內容',
        }


class Comment_Form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('credit','comment',)
        labels = {
            'credit':'給送養者評價',
            'comment':'寫下你對對方的評語',
        }
        widgets = {
            'credit': forms.RadioSelect(renderer=HorizRadioRenderer)
        }

Project/pets_adopt/views/blog.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from pets_adopt.forms import Blog_Post
from pets_adopt.models import Pets,Adopt
from pets_adopt.models import Blog
from django.utils import timezone



def post_list(request, pets_id):
    template = 'pets_adopt/blog/post_list.html'
    pet = get_object_or_404(Pets, id=pets_id)
    blog = Blog.objects.filter(pet = pet)
    can_post = False
    if (pet.pet_owner == request.user):
        can_post = True
    return render(request, template, {'posts': blog, 'pet': pet,'can_post':can_post})


def post_new(request, pets_id):
    template = 'pets_adopt/blog/post_new.html'
    pet = get_object_or_404(Pets, id=pets_id)
    if request.method == 'POST':
        form = Blog_Post(request.POST, request.FILES)
        if form.is_valid:
            image_file = request.FILES["photo"]
            blog = form.save(commit=False)
            blog.photo = image_file
            blog.author = request.user
            blog.pet= pet
            blog.published_date = timezone.now()
            blog.save()
            return redirect('post_list', pets_id=pet.id)
    else:
        form = Blog_Post()
        return render(request, template, {'pet': pet, 'form': form})


def question_index(request):
    template = 'pets_adopt/extra/questionnaire.html'
    return render(request, template, {'nbar': 'question'})


def question_handle(request):
    template = 'pets_adopt/extra/question_result.html'
    result = 0
    right = False
    for i in range(1, 11):
        if request.POST.get('Q' + str(i)) == 'T':
            result += 10
    if result >= 70:
        right = True
    return render(request, template, {'right': right, 'result': result, 'nbar': 'question'})

Project/pets_adopt/views/center.py
#coding:utf-8
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from pets_adopt.models import Pets,Adopt,NewUser

@login_required
def main(request,user_id): #會員中心，可修改個人資料及寵物資料，以及觀看送領養紀錄
    user = get_object_or_404(NewUser, id=user_id)
    template_name = "pets_adopt/member_center/main.html"
    return render(request,template_name,{'user': user,'nbar':'memcenter'})


@login_required
def my_pet(request, user_id): #屬於我的寵物
    template_name = "pets_adopt/member_center/my_pet.html"
    user = get_object_or_404(NewUser, id=user_id)
    pet = Pets.objects.filter(pet_owner=user)
    return render(request, template_name, {'user':user,'pet':pet,'nbar':'memcenter'})

# Adopt.mode=0:待批準,1:通過,2:拒絕,3:待領養者確認,4:待送養者確認
@login_required
def sending_pet(request, user_id): #送養中的寵物
    template_name = "pets_adopt/member_center/sending_pet.html"
    user = get_object_or_404(NewUser, id=user_id)
    pet = Pets.objects.filter(pet_publisher=user, state=0)
    return render(request, template_name, {'user':user,'pet':pet,'nbar':'memcenter'})

@login_required
def receiving_pet(request, user_id): #想領養的寵物
    template_name = "pets_adopt/member_center/receiving_pet.html"
    user = get_object_or_404(NewUser, id=user_id)
    adopts = Adopt.objects.filter(adopt_person=user) #這個人的所有領養單
    return render(request, template_name, {'user':user,'adopt':adopts,'nbar':'memcenter'})

Project/pets_adopt/views/user.py
#coding:utf-8
from django.contrib.auth import login, authenticate
from django.contrib import messages,auth
from pets_adopt.forms import UserForm,User_Edit
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from pets_adopt.models import NewUser,Adopt,Pets,Comment


def user_signup(request):
    template_name = 'pets_adopt/signup.html'
    if request.method == 'POST':
        form = UserForm(request.POST,request.FILES)
        if form.is_valid():
            image_file = request.FILES["photo"]
            user_name = request.POST['username']
            password = form.clean_password2()
            form.save(commit=False)
            form.photo = image_file
            form.save()
            user = authenticate(username = user_name, password = password)
            if user.is_active:
                login(request,user)
                messages.success(request,u'註冊成功並登錄')
            return redirect('index')
    else:
        form = UserForm
    return render(request,template_name,{'form': form,'nbar':'signup'})

@login_required
def user_edit(request,user_id): #要尋找更好寫法
    user = get_object_or_404(NewUser, id=user_id)
    template_name = "pets_adopt/user_edit.html"
    if request.method =='POST':
        form = User_Edit(request.POST, instance=user)
        form.save()
        messages.success(request,u'修改成功')
        return redirect('index')
    else:
        form = User_Edit(instance = user)
        return render(request,template_name,{'form':form,'user':user})


def user_detail(request,user_id):
    usr = get_object_or_404(NewUser, id=user_id)
    template_name = "pets_adopt/user_detail.html"
    all_comment = Comment.objects.filter(person = usr)
    all_pet = Pets.objects.filter(pet_owner=usr)
    good = 0
    ok = 0
    bad = 0
    for cmt in all_comment: #顯示這個人的評價
        if cmt.credit == 0:
            good += 1
        elif cmt.credit == 1:
            ok += 1
        elif cmt.credit == 2:
            bad += 1
    return render(request,template_name, {'usr':usr,'all_comment':all_comment,'good':good,'ok':ok,'bad':bad,'all_pet':all_pet})




"""
def user_login(request):
    template_name = 'pets_adopt/login.html'
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid:
            user_name = request.POST['username']
            password = request.POST['password']
            user = authenticate(username = user_name,password = password)
            if user is not None and user.is_active:
                login(request, user)
                    return redirect('index')

    else:
        form = LoginForm()
        return render(request,template_name,{'form': form})
"""

"""

def user_logout(request):
    auth.logout(request)
    return redirect('index')
"""

Project/templates/pets_adopt/adopt_action/adopt_success1.html
<!-- adopt_yes,adopt_person -->
{% extends "pets_adopt/base.html" %}
{% block content %}
    <h3>恭喜你的{{ adopt_yes.adopt_pet }}已找到收養人,以下是收養人的聯絡資訊</h3><br/>
    <table align="center" class="table">
    <tr><td>姓名</td><td>{{ adopt_person.name }}</td></tr>
    <tr><td>性別</td><td>{{ adopt_person.get_gender_display }}</td></tr>
    <tr><td>E-mail</td><td>{{ adopt_person.email }}</td></tr>
    <tr><td>身份證字號</td><td>{{ adopt_person.id_card_num }}</td></tr>
    <tr><td>手機號碼</td><td>{{ adopt_person.mobile }}</td></tr>
    <tr><td>家電</td><td>{{ adopt_person.home_tel }}</td></tr>
    <tr><td>Facebook</td><td><a href="{{ adopt_person.facebook }}" target="_blank">{{ adopt_person.name }}</a></td></tr>
    <tr><td>Line ID</td><td>{{ adopt_person.line }}</td></tr>
    <tr><td>個人簡介</td><td>{{ adopt_person.profile }}</td></tr>
    <tr><td>證件照</td><td><img src="{{ MEDIA_URL }}{{ adopt_person.photo }}"></td></tr>
    </table>

    <h3>等待對方確認中</h3><br>
    <br/>
{% endblock %}

Project/templates/pets_adopt/adopt_action/adopt_success2.html
<!-- adopt_yes,publisher -->
{% extends "pets_adopt/base.html" %}
{% block content %}
    <h3>你已確定要領養{{ adopt_yes.adopt_pet }}以下是送養人的聯絡資訊</h3><br/>
    <table align="center" class="table">
    <tr><td>姓名</td><td>{{ publisher.name }}</td></tr>
    <tr><td>性別</td><td>{{ publisher.get_gender_display }}</td></tr>
    <tr><td>E-mail</td><td>{{ publisher.email }}</td></tr>
    <tr><td>身份證字號</td><td>{{ publisher.id_card_num }}</td></tr>
    <tr><td>手機號碼</td><td>{{ adopt_person.mobile }}</td></tr>
    <tr><td>家電</td><td>{{ publisher.home_tel }}</td></tr>
    <tr><td>Facebook</td><td><a href="{{ publisher.facebook }}" target="_blank">{{ publisher.name }}</a></td></tr>
    <tr><td>Line ID</td><td>{{ publisher.line }}</td></tr>
    <tr><td>個人簡介</td><td>{{ publisher.profile }}</td></tr>
    <tr><td>證件照</td><td><img src="{{ MEDIA_URL }}{{ publisher.photo }}"></td></tr>
    </table>

    <a href="{% url 'user_detail' user_id=publisher.id %}">他的個人簡介</a>
    <br/>
    <h3>請在30天內與送養人聯繫，並完成送養，否則將系統將會取消</h3>
{% endblock %}

Project/templates/pets_adopt/adopt_action/adopt_success3.html
<!-- adopt_yes,pet -->
{% extends "pets_adopt/base.html" %}
{% block content %}
    <div class="form-page-contain">
    <h2>恭喜你的{{ adopt_yes.adopt_pet }}已成功送養給{{ adopt_yes.adopt_person }}</h2><br>
    <h4>記得提醒對方，時常po寵物動態，讓大家了解{{ adopt_yes.adopt_pet }}在新家的生活:))</h4>
    <form method="POST" action="{% url 'pet_adopt_last_confirm' adopt_id=adopt_yes.id %}"
            class="form-horizontal" id="adopt-success3-form">
        {% csrf_token %}
        {{ form.non_field_errors }}
    <div class="form-group">
    {{ form.credit.errors }}
    <label for="{{ form.credit.id_for_label }}" class="col-sm-2 control-label">給送養者評價:</label>
        <div class="col-sm-10">
        {{ form.credit }}
        </div>
    </div>

          <div class="form-group">
    {{ form.comment.errors }}
    <label for="{{ form.comment.id_for_label }}" class="col-sm-2 control-label">對對方的評語:</label>
        <div class="col-sm-10">
        {{ form.comment }}
        </div>
    </div>

        <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">送出</button>
        </div>
    </div>
    </form>
    </div>
{% endblock %}

Project/templates/pets_adopt/adopt_action/check_confirm.html
<!--object:adopts_confirmed, adopts_not_yet -->
{% extends "pets_adopt/base.html" %}
{% block content %}
    <br>
    <div class="row index-pet-show">
      <div class="col-lg-4">
    <h2>送養者已確認，等待你領養的寵物：</h2>
    {% if adopts_confirmed %}
        {% for adopt in adopts_confirmed %}
            <p>{{ adopt.adopt_pet }}</p> <br/>
            <a href="pet_confirm/2/{{ adopt.id }}">
                <button>確定領養</button>
            </a>
        <br/>
        {% endfor %}
        {% else %}
            <p>無</p>
    {% endif %}
      </div>
      <div class="col-lg-4">
    <h2>送養者已拒絕你的認養：</h2>
    {% if adopts_reject %}
        {% for adopt in adopts_reject %}
        <a href="{% url 'pet_detail' pets_id=adopt.adopt_pet.id %}" target="_blank">
            <button type="submit" class="btn btn-default">{{ adopt.adopt_pet }}</button>
        </a><br/>
        {% endfor %}
        {% else %}
            <p>無</p>
    {% endif %}
      </div>
      <div class="col-lg-4">
    <h2>還沒被送養者確認是你的寵物</h2>
    {% if adopts_not_yet %}
    {% for adopt in adopts_not_yet %}
        <a href="{% url 'pet_detail' pets_id=adopt.adopt_pet.id %}" target="_blank">
            <button type="submit" class="btn btn-default">{{ adopt.adopt_pet }}</button>
        </a><br/>
    {% endfor %}
        {% else %}
        <p>無</p>
    {% endif %}
      </div>
    </div>
{% endblock %}

Project/templates/pets_adopt/adopt_action/check_response.html
<!--object:standby_pets,sent_pets,already -->
{% extends "pets_adopt/base.html" %}
{% block content %}
    <br>
    <div class="row index-pet-show">
      <div class="col-lg-4">
    <h2>等你出門把寵物送出去：</h2>
    {% if already %}
        {% for already in already %}
            {{ already.adopt_pet }} <br>
            <a href="pet_confirm/last/{{ already.id }}">
                <button>已完成領養</button>
            </a>
                <button>未完成領養</button>
        {% endfor %}
        {% else %}
            <p>無</p>
    {% endif %}
      </div>
      <div class="col-lg-4">
    <h2>認養人列表：</h2>
    {% if standby_pets %}
        {% for each_standby_pets in standby_pets %}
            有人要養:
            <p>{{ each_standby_pets.adopt_pet }}</p> <br/>
            那個人是:
            <a href="{% url 'user_detail' user_id=each_standby_pets.adopt_person.id %}" target="_blank">{{ each_standby_pets.adopt_person }}</a>
            理由:
            <p>{{ each_standby_pets.content }}</p>
            <a href="pet_confirm/1/{{ each_standby_pets.id }}">
                <button type="submit" class="btn btn-default">就是他了</button>
            </a>
            <br/>
        {% endfor %}
        {% else %}
            <p>無</p>
    {% endif %}
      </div>
      <div class="col-lg-4">
    <h2>已經送養的寵物：</h2>
    {% if sent_pets %}
        {% for each_sent_pets in sent_pets %}
            <a href="{% url 'pet_detail' pets_id=each_sent_pets.adopt_pet.id %}" target="_blank">
                <button type="submit" class="btn btn-default">{{ each_sent_pets.adopt_pet }}</button>
            </a><br/>
        {% endfor %}
        {% else %}
            <p>無</p>
    {% endif %}
      </div>
{% endblock %}

Project/templates/pets_adopt/adopt_action/comment_success.html
{% extends "pets_adopt/base.html" %}
{% block content %}

    <p>成功送出評價!</p><br/>
    <p>{{ comment.person }}的優良評價是{{ good }} 普通評價是{{ ok }} 不良評價是{{ bad }}</p> <br>
    <p>你對他的評價：{{ comment.get_credit_display }}</p> <br/>
    <p>原因：{{ comment }}</p>
{% endblock %}

Project/templates/pets_adopt/adopt_action/sent_form.html
{% extends "pets_adopt/base.html" %}
{% block content %}
<form method="POST" action="{% url 'pet_adopt' pets_id=pet.id %}" class="form-horizontal" id="adopt-sent-form">
    <h2>你要領養的寵物是: {{ pet.pet_name }}</h2>
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
    {{ form.content.errors }}
    <label for="{{ form.content.id_for_label }}" class="col-sm-3 control-label">說說認養理由:</label>
        <div class="col-sm-9">
        {{ form.content }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-default">送出</button>
        </div>
    </div>
</form>
{% endblock %}

Project/templates/pets_adopt/adopt_action/sent_success.html
{% extends "pets_adopt/base.html" %}
{% block content %}
    <h1>成功送出領養資訊</h1>
    <p>你要領養的狗是: {{ pet.pet_name }} <br>
    <p>認養理由：</p><br>
    {{ adopt.content }}
{% endblock %}